# Generated by Django 5.2.3 on 2025-06-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_question_country_question_subject_question_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='questions',
            field=models.ManyToManyField(related_name='person', to='myApp.question'),
        ),
    ]
